# Server Configuration
server:
  port: 8085

# Database Configuration
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/order_service_db
    username: order_user
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

# Logging Configuration
logging:
  level:
    org.springframework: INFO
    com.myapp: INFO
    org.springframework.security: INFO  # Enable detailed security logging
